### ISSUE TITLE
Need a deployment mechanism

### ISSUE THREAD

**Issue by dchassin** [slacgismo/docs-browser#5]
The installation process needs a Python script to deploy on cloud platforms like AWS, e.g., simple script that works as follows:
~~~
bash$ git clone https://github.com/slacgismo/docs-browser
bash$ cd docs-browser
bash$ nano src/config.js
bash$ ./deploy.sh src www.mysite.org
~~~

**Comment by jongoncalves** [comment]
This is already covered in our CI pipeline in circleci. After the project successfully builds in master, it deploys to s3. Once we move over the DNS entry there will no other loose ends.

Is there something else you want to capture with this issue or can we close it?

**Comment by dchassin** [comment]
I like the single deployment approach of goings through `docs.slacgismo.org`. However, if we make this the preferred method, we ned to support `GET` queries in the manner of the prototype, e.g., `GET /index.html?owner=dchassin&project=gridlabd&branch=develop&folder=Module&doc=/README.md` should open the browser on my fork of `gridlabd` on the `develop` branch, with the `Module` folder open, and `README.md` document displayed.

**Comment by jongoncalves** [comment]
Yep, I'll create a task to capture that right now.

**Comment by jongoncalves** [comment]
Work will now be capture by:
https://github.com/slacgismo/docs-browser/issues/20
